### ISSUE TITLE
Crash upon removing all combat ships

### ISSUE THREAD

**Issue by skessler79** [niatahl/tahlan-shipworks#5]
This fatal crash occurs immediately after removing all combat ships from my fleet.

> 3921331 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.IllegalArgumentException: Cannot round NaN value.
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1132)
	at org.niatahl.tahlan.listeners.LegioFleetInflationListener$Companion.addSMods(LegioFleetInflationListener.kt:71)
	at org.niatahl.tahlan.hullmods.DaemonHeart.advanceInCampaign(DaemonHeart.kt:174)
	at com.fs.starfarer.campaign.fleet.CampaignFleet.advance(Unknown Source)
	at com.fs.starfarer.campaign.BaseLocation.advance(Unknown Source)
	at com.fs.starfarer.campaign.StarSystem.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	
Could this be caused by a divide by zero error in `LegioFleetInflationListener.kt:70-71`? Seems like numShips will be 0 if there's only civilian ships in your fleet?

I don't know Kotlin so I'm just eyeballing it and could be wrong entirely.

**Comment by niatahl** [comment]
I forgot I changed it to only count combat ships, yeh. Adding a fix.
