### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot round NaN value.

### ISSUE THREAD

**Issue by RichoDemus** [niatahl/tahlan-shipworks#6]
Hey friend and thanks for an awesome mod, I have a little problem.

so on my save I'm flying a single ship and docking at a pirate station and I get the following:

```
786703 [Thread-3] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.IllegalArgumentException: Cannot round NaN value.
java.lang.IllegalArgumentException: Cannot round NaN value.
	at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1132)
	at org.niatahl.tahlan.listeners.LegioFleetInflationListener$Companion.addSMods(LegioFleetInflationListener.kt:71)
	at org.niatahl.tahlan.hullmods.DaemonHeart.advanceInCampaign(DaemonHeart.kt:174)
	at com.fs.starfarer.campaign.fleet.FleetData.syncIfNeeded(Unknown Source)
	at com.fs.starfarer.campaign.fleet.FleetData.sort(Unknown Source)
	at com.fs.starfarer.campaign.fleet.FleetData.sort(Unknown Source)
	at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.createFleet(FleetFactoryV3.java:468)
	at com.fs.starfarer.api.impl.campaign.submarkets.BaseSubmarketPlugin.addShips(BaseSubmarketPlugin.java:530)
	at com.fs.starfarer.api.impl.campaign.submarkets.OpenMarketPlugin.updateCargoPrePlayerInteraction(OpenMarketPlugin.java:72)
	at exerelin.campaign.submarkets.Nex_OpenMarketPlugin.updateCargoPrePlayerInteraction(Nex_OpenMarketPlugin.java:12)
	at stelnet.board.query.provider.MarketProvider.updateSubmarkets(MarketProvider.java:71)
	at stelnet.board.query.provider.MarketProvider.updateMarket(MarketProvider.java:55)
	at stelnet.board.query.MarketUpdater.updateMarket(MarketUpdater.java:86)
	at stelnet.board.query.MarketUpdater.advance(MarketUpdater.java:47)
	at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

let me know if there's anything I can do to assist you, I also attached my save in case you want to try to reproduce it
[save_RichoDemus_6052405716411762977.zip](https://github.com/niatahl/tahlan-shipworks/files/11972267/save_RichoDemus_6052405716411762977.zip)

**Comment by niatahl** [comment]
Known bug. Fix soonish. Till then avoid having no combat ships in your fleet.
